version: '2'
services:
  httpd:
    build: ./httpd
    volumes:
      - ./httpd/cert:/mnt
    ports:
      - "443:443"
    env_file:
      - .env
    restart_policy:
      delay: 5s
      max_attempts: 3
      window: 120s
  softlayer-sql:
    build: ./mysql
    hostname: softlayer-sql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart_policy:
      delay: 5s
      max_attempts: 3
      window: 120s
  softlayer:
    build: ./web
    hostname: softlayer
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    restart_policy:
      delay: 5s
      max_attempts: 3
      window: 120s
  python:
    build: ./python
    hostname: python
    volumes:
      - ./python:/opt
    env_file:
      - .env
    restart_policy:
      delay: 5s
      max_attempts: 3
      window: 120s
